name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14
    - name: Install dependencies
      run: yarn install
    - name: Configure Git
      run: git config user.email "abductee@gmail.com" && git config user.name "braintrain"
    - name: Check the current working directory
      run: pwd
    - name: Deploy
      run: yarn deploy
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
